name: Scala CI
on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - 'master'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
      - uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - run: |
        chmod -x gradlew
        ./gradlew clean build
      - uses: actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/**/*.jar
